### ISSUE TITLE
This package depends on `web3-eth-abi` but this is not reflected in `package.json`

### ISSUE THREAD

**Issue by romang-at-guarda-co** [vechain/thorify#111]
#### Environment information

Thorify version: `1.5.3`<br>

#### Expected behaviour

`web3-eth-abi` is in `package.json` as a dependency

#### Actual behaviour

`web3-eth-abi` is not in `package.json`

**Comment by libotony** [comment]
@romang-at-guarda-co thank you for reporting, solved in v1.5.4
