### ISSUE TITLE
Get private key to sendTransaction

### ISSUE THREAD

**Issue by raedbenz** [vechain/thorify#115]
Hello,

I have created accounts with Sync and Sync2 to use during development of a DAPP in test net.
According to api docs i need a private key to add to wallet in order to call sendTransaction(). 
How can I get PK plz since cant export it from sync.
I can export keystore, but is there a way to PK from it?
Any tutorials to use signed transactions are much appreciated. 
Thanks

**Comment by libotony** [comment]
Sync/Sync2 does not support exporting private keys. If you want to get your own private key, take a look at [thor-devkit.js](https://github.com/vechain/thor-devkit.js#mnemonic--keystore).

BTW, [connex](https://github.com/vechain/connex/tree/master/packages/connex) is recommended for building a DAPP.

**Comment by raedbenz** [comment]
Can I use connex from nodejs backend, Without user interaction ?

**Comment by libotony** [comment]
Yes. Package `connex` was designed to only work in the browser, you need to compose [Framework](https://github.com/vechain/connex/tree/master/packages/framework) and [Driver](https://github.com/vechain/connex/tree/master/packages/driver) together. Here is an [example](https://github.com/vechain/connex/blob/master/packages/repl/src/main.ts#L26)

**Comment by raedabusanad** [comment]
I have captured the whole workflow in a blog post to help new comers

[https://raed-abusanad.medium.com/vechain-developer-guide-81d5e0f10aa4](https://raed-abusanad.medium.com/vechain-developer-guide-81d5e0f10aa4)

I deployed Smart Contract using Inspector app from Sync v1. if you think there is a better plz let me know

Thanks
