### ISSUE TITLE
Get all events doesn't work in the latest version of thorify 

### ISSUE THREAD

**Issue by mastercodingbear** [vechain/thorify#144]
Hi there,

#### Environment information

Thorify version: `1.6.0`<br>
Web3 version: `1.7.1`<br>

#### Expected behaviour
Can't fetch all past events

#### Actual behaviour
contractInstance.events.getPastEvents('allEvents') doesn't work properly.
contractInstance.events.getPastEvents('MyEvent') doesn't work properly.

#### Steps to reproduce the behaviour
After upgrading, new version can't fetch all events

#### Stacktrace

````
[stacktrace]
````

**Comment by libotony** [comment]
You need to specify the range in the options, web3.js changed the behavior for safety reasons. Default `from` has been set to max number in case the result set is huge. I would suggest `getPastEvents('allEvnents', range: {unit: 'block', from : <number>, to: <number>}, options:{limit<number>, offset: <number>})`
