### ISSUE TITLE
send transaction to accounts in peer nodes

### ISSUE THREAD

**Issue by SriramRS** [vechain/thorify#15]
Is it possible to get list of accounts in particular node.so that we can try sending transaction to accounts in peers.Also whether it is  possible to send **private transaction between nodes** in VeChain test network.

**Comment by libotony** [comment]
see https://github.com/vechain/thorify#send-transaction

VeChainThor's node client doesn't keep private key

**Comment by SriramRS** [comment]
yeah that's ok.. But can we able to send transaction to accounts in peers like sending transactions between accounts in same node?

**Comment by libotony** [comment]
@SriramRS what do you mean by "accounts in peers" ?

**Comment by SriramRS** [comment]
@libotony transaction between accounts in different nodes..

**Comment by libotony** [comment]
@SriramRS there is no accounts in nodes
