### ISSUE TITLE
Question: roadmap for implementing future web3 methods

### ISSUE THREAD

**Issue by boye** [vechain/thorify#22]
Hi there,

Are there any plans to implement more web3 methods?

Cheers and keep up the good work!
Boye

**Comment by libotony** [comment]
@boye which method would you like to have in thorify ?

**Comment by boye** [comment]
@libotony thank you for your quick response.

I was looking at [Ethstats](https://ethstats.net/) and tried to build a similar dashboard for VeChain Thor. So I started with forking the [Ethereum Network Intelligence API](https://github.com/cubedro/eth-net-intelligence-api) and implementing Thorify.

I got it working in terms of connecting with the [REST API](https://api.vechain.tools/doc/swagger-ui/) but it chokes on some methods like: getHashrate, getGasPrice, isMining etc. I have paused my side project for now, but it would be awesome if developers would be able to build such a dashboard for Vechain Thor.

**Comment by libotony** [comment]
@boye Thank you for your support, it's really a good idea to build dashboard like ethstats.

**Comment by boye** [comment]
Again, thank you! I will definitely continue investigating the architecture. As for the design of VeChainThor Stats, do you recommend using the whitepaper as starting point or maybe some other repository and look at existing code?

**Comment by libotony** [comment]
Yes definitely you can read the technical part of the [white paper](https://cdn.vechain.com/vechainthor_development_plan_and_whitepaper_en_v1.0.pdf), you can get more technical info from [github wiki](https://github.com/vechain/thor/wiki) 、 [medium](https://medium.com/@vechainofficial)  or join our [gitter](https://gitter.im/vechain/thor) to talk with the team and the community

**Comment by boye** [comment]
Awesome! I will close this issue for now 👍
