### ISSUE TITLE
Make events RxJS / Observable compatible

### ISSUE THREAD

**Issue by molekilla** [vechain/thorify#39]
Current way to read events requires polling for `getPastLogs` or `getPastEvents`. If would be nice if we could have a reactive way to listen for event streams using either RxJS or ES Observables.

Example:

```
contractInstance.getPastEvents('transfer').subscribe(log =>{
// one log instead of an array of logs
  console.log(log)
}, 
() => console.log('completed'), 
e => console.log)
```

**Comment by libotony** [comment]
Thor is working on support subscription see vechain/thor#91

**Comment by libotony** [comment]
Regarding the subscription support, it's a working in progress feature, API doc and tests are not finished, but still, you can try that following the doc in web3 1.0 branch. Thorify follows web3's specification, as far as I know, if you want to use RxJS and web3 you need to do some wrap yourself.

**Comment by libotony** [comment]
Subscription support is added at version 1.0.0, you can check [API doc](https://vechain.github.io/thorify/#/?id=web3ethsubscribe) for detailed info

**Comment by molekilla** [comment]
Does Contracts events works with websocket? And which `thor` version works with ws enabled thorify version?

**Comment by libotony** [comment]
> Does Contracts events works with websocket?

Yes, see subscribe('logs') and contract.events

> And which thor version works with ws enabled thorify version?

v1.0.2 and later, see [README.md](https://github.com/vechain/thorify#subscriptions-support)

**Comment by molekilla** [comment]
Found a bug:
Code
```
        const evt = this.senderContract.events.LogGrantTokens({
            fromBlock: blockNumber
        })
```
Error
```
browser.js:4 Uncaught Error: ws does not work in the browser. Browser clients must use the native WebSocket object
    at new module.exports (browser.js:4)
    at ThorProvider.ManagerSubscription (index.js:85)
    at ThorProvider.sendAsync (index.js:34)
    at RequestManager.send (index.js:132)
    at Subscription.subscribe (subscription.js:249)
    at Contract.web3.eth.Contract._on (contracts.js:78)
```

I had the same issue with `ws`, you need to use native websocket if client is a browser

**Comment by libotony** [comment]
fixed in #59

**Comment by libotony** [comment]
I tried in my browser(Google Chrome V.69), connects to my local node, seems to be kept in the connection for a long time(I tested for 30 minutes), can you check if there is any proxy software between your client and thor? As far as I know, the proxy software will have a default option for the proxy timeout.

**Comment by libotony** [comment]
To debug, I use [debug package](https://www.npmjs.com/package/debug) to log debug info, you set the debug filter to 'thor:*' and will get the close info, this will help

**Comment by molekilla** [comment]
Thanks, will test it out

**Comment by molekilla** [comment]
@libotony It is not working, tested with different thor test net servers.

Some info:

1. I'm requesting `thor` without `wss://` (if I use it it breaks), while `geth` uses wss protocol without problems/
2. `geth` sends `Upgrade` headers back to server, while `thor` is not sending those (More info here http://nginx.org/en/docs/http/websocket.html)
3. The ws error code is 1006. I think is only browser related, I wonder if backend requires the same headers. So far our implementation with backend calling ws seems to work.

Let me know further.

Thanks

**Comment by molekilla** [comment]
Closing. 1.0.3 fixes it
