### ISSUE TITLE
Suggestion: web3.eth.getAccounts implementation

### ISSUE THREAD

**Issue by totuet** [vechain/thorify#44]
I was looking to use the web3.eth.getAccounts method from the ethereum javascript api. Apparently this is not implemented yet in thorify. Any plans on this?

https://web3js.readthedocs.io/en/1.0/web3-eth.html#getaccounts

**Comment by libotony** [comment]
Unlike ethereum's implementation, thor‘s node doesn't store accounts since getAcoounts returns the accounts that the nodes "controls", no plan for now

**Comment by totuet** [comment]
Ok thanks. 
Any other method I could use to retrieve a list of addresses containing a minimum amount of x vet?

**Comment by libotony** [comment]
Do you mean all the addresses on the blockchain?

**Comment by totuet** [comment]
Yes indeed. Actually no idea if this is feasible. But I'm just asking. I'll close this thread afterwards.

**Comment by libotony** [comment]
You need to walk through all the blocks and transactions like the explorers did.

**Comment by totuet** [comment]
Ok thanks for your help. Have a nice day!
