### ISSUE TITLE
Error: deploy contract by sending tx

### ISSUE THREAD

**Issue by dinn2018** [vechain/thorify#6]
tx object {
        from: "0x7567d83b7b8d80addcb281a71d54fc7b3364ffed",
        to: null,
        data: contractCode,
        gas: 200000,
        value: 100,
    }

when send this tx, returns `The transaction receipt didn't contain a contract address.`

**Comment by libotony** [comment]
cause by web3-core-method, in the check transaction receipt function the code doesn't check if the transaction is executed successfully, [source code](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/index.js#L297)
