### ISSUE TITLE
web3.eth.contract.deploy incorrect arguments structure

### ISSUE THREAD

**Issue by OliverNChalk** [vechain/thorify#60]
#### Environment information

Thorify version: `1.0.0`<br>
Web3 version: `1.0.0-beta.36`<br>

#### Expected behaviour
When calling contract.deploy, I was expecting to only need to past my bytecode in. This is outlined in the API Reference:
![image](https://user-images.githubusercontent.com/11343499/45805995-37c1f180-bcc0-11e8-8c8b-50c50fe0713e.png)

#### Actual behaviour
When calling the function it threw me an error until I passed an empty array in first (I did not have any arguments to execute).
![image](https://user-images.githubusercontent.com/11343499/45800549-887e1e00-bcb1-11e8-94f1-d1f7e44400dd.png)

#### Steps to reproduce the behaviour
1. Attempt to deploy a contract using only bytecode with no constructor arguments.
2. Observe error.

**Comment by libotony** [comment]
`dependsOn` is the param for `send` function,  not to deploy and you need to call deploy like the following:

``` javascript
contractToDeploy.deploy({data: payload}).send()
```

**Comment by OliverNChalk** [comment]
My bad, wrong image in clipboard. I have updated the issue now. When passing in `{data: payload}` it works the same as `[], payload`. It would seem that arguments is expected before data, although it is optional?

**Comment by libotony** [comment]
`data` is required and only `arguments` is optional

**Comment by OliverNChalk** [comment]
Yes, `data` is required, however, the function expects `arguments` to be passed first, followed by data. This is despite the documentation suggesting otherwise.
That is why this code:
![produces_err](https://user-images.githubusercontent.com/11343499/45808634-8d010180-bcc6-11e8-987b-747f99662eb2.png)
Produces this error:
![deploy_error](https://user-images.githubusercontent.com/11343499/45808601-65119e00-bcc6-11e8-9e45-e52d73aa377b.png)

And why this code:
![code_no_error](https://user-images.githubusercontent.com/11343499/45808675-aa35d000-bcc6-11e8-833f-f54fdb172e57.png)
Produces no error:
![no_error](https://user-images.githubusercontent.com/11343499/45808749-db160500-bcc6-11e8-8cc2-0724f0bce12c.png)
TX: https://testnet.veforge.com/transactions/0x7c9d310e317bd4326fa644a3050eb0c9eacc9582839c74fd025bbe26629818d4

**Comment by libotony** [comment]
`deploy` accepts an object as the argument, it should be like this

``` javascript
contractToDeploy.deploy({
    data: payload,
    arguments: [] // arguments can be omitted
})
```
