### ISSUE TITLE
web3.eth.sendTransaction no return 

### ISSUE THREAD

**Issue by txsdev** [vechain/thorify#66]
#### Environment information

Thorify version: `1.0.3`<br>
Web3 version: `^1.0.0-beta.36`<br>

#### Expected behaviour
return txid

#### Actual behaviour
no return

#### Code
   web3.eth.accounts.wallet.add(private_key);
web3.eth.sendTransaction(tx).then( (result) => {
        console.log(result)
    }).catch( (error) => {
        console.log(error)
    })

Note: transfer is success but no return txhash ?

**Comment by libotony** [comment]
`Thorify@1.*` and later need work with `thor@1.0.2` or later

**Comment by txsdev** [comment]
@libotony  Thx , it's work!!!

**Comment by txsdev** [comment]
@libotony Thx, it work!!!
