### ISSUE TITLE
delegatecall does not works with thorify

### ISSUE THREAD

**Issue by ParminderParmar** [vechain/thorify#76]
Hi ,

#### Environment information
Thorify version: `1.0.4`<br>
Web3 version: `1.0.0-beta.36`<br>

#### Expected behaviour
Thorify should support proxy patterns for smart contracts for upgradability purpose.

#### Actual behaviour
Getting transaction reverted when using proxy contract to reach logic contract.
When running test using truffle it works fine.

####Architecture of what i am trying to achieve
ProxyContract -----> LogicContract

Proxy contract contains below fallback function which redirects calls to LogicContract:
https://github.com/zeppelinos/labs/blob/ff479995ed90c4dbb5e32294fa95b16a22bb99c8/upgradeability_using_eternal_storage/contracts/Proxy.sol 

  function () payable public {
    address _impl = implementation();
    require(_impl != address(0));

    assembly {
      let ptr := mload(0x40)
      calldatacopy(ptr, 0, calldatasize)
      let result := delegatecall(gas, _impl, ptr, calldatasize, 0, 0)
      let size := returndatasize
      returndatacopy(ptr, 0, size)

      switch result
      case 0 { revert(ptr, size) }
      default { return(ptr, size) }
    }

#### Steps to reproduce the behaviour
Use the contracts in below link with thorify.
https://github.com/zeppelinos/labs/tree/ff479995ed90c4dbb5e32294fa95b16a22bb99c8/upgradeability_using_eternal_storage/contracts

**Comment by ParminderParmar** [comment]
I am using below API from Thorify.

return await web3.eth.sendSignedTransaction( rawTransaction ).catch((e) => {
    console.log(e)
});

**Comment by ParminderParmar** [comment]
Hi Team ,

An updates regarding this issue ? This is impacting our project timelines.

**Comment by qianbin** [comment]
@ParminderParmar How did you build the `rawTransaction`?  Could you please post the `rawTransaction`?

**Comment by ParminderParmar** [comment]
Hi @qianbin ,

Thanks for getting back to me.

I am using below function to create a signed transaction.

const thorify = require('thorify').thorify;
const thorAPI = require('thor-devkit');




let getSignedRawTransaction = async ( transactionParams, privateKey ) => {
	let transaction = new thorAPI.Transaction( transactionParams );
	let signingHash = thorAPI.cry.blake2b256(transaction.encode());
	let pk = Buffer.from( privateKey.substring( 2 ), 'hex' );
	transaction.signature = thorAPI.cry.secp256k1.sign( signingHash, pk ).toString( 'hex' );
	let rawTransaction = transaction.encode();
	rawTransaction = "0x" + rawTransaction.toString('hex');

	return rawTransaction;
};


const contract = new web3.eth.Contract( logicContractInterface, logicContractAddress );
const methodData = contract.methods.[METHOD_NAME]( ).encodeABI();
const transactionParams = await thorTransaction( {
			from: fromAccount,
			clauses: [
				{
					'data': methodData,
					'value': 0,
					'to': proxyAddress
				}
			]
		} );

const rawTransaction = getSignedRawTransaction(transactionParams, privateKey)

**Comment by libotony** [comment]
Hi @ParminderParmar please post the `RawTransaction` here we need check the signed transaction and it would be more helpful if you can provide the contract address and transaction on testnet

**Comment by ParminderParmar** [comment]
Hi,

Please find below requested details : 

RawTransaction: 0xf8fa81c78503a72db1188202d0f89ef89c94e0effac9c79269bada708695138ed03c3a45a33080b884c354c9150000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006300000000000000000000000000000000000000000000000000000000000000057465737431000000000000000000000000000000000000000000000000000000808398967f808404d9fe06c0b841fdb63811a2badb630648b964f71bcdbcad2b70e432fcda1025a8eb7892c342985bc95eab9b4cfdbd254461878445442cbc977ecf6f602be452c835423fd565ec01

This is not yet deployed on test net. But if needed you can use the sample project to replicate the issue ( rawtransaction will be different 
[proxy_poc.zip](https://github.com/vechain/thorify/files/2855247/proxy_poc.zip)
)

**Comment by ParminderParmar** [comment]
Sample project seems to be working on test net so not a problem with delegatecall. Will check at my end.
