### ISSUE TITLE
Suggestion about initialization

### ISSUE THREAD

**Issue by amazingandyyy** [vechain/thorify#8]
current way
```
const web3 = new Web3();
thorify(web3, "http://localhost:8669");
web3.eth.getBlock("latest").then(res=>console.log(res));
// what? we just upgrade the web3 like that?
```
I suggest change to this way:
```
const web3 = thorify(new Web3(), "http://localhost:8669");
web3.eth.getBlock("latest").then(res=>console.log(res));
```
make `thorify()` return a `web3 instance` which extent the original web3 object and connect to thor blockchain.

I think this way will be more idiomatic for node/js user/community.

**Comment by libotony** [comment]
Will do that in the next version

**Comment by libotony** [comment]
updated in #10
