### ISSUE TITLE
recovering address from signature

### ISSUE THREAD

**Issue by adaaaam7777** [vechain/thorify#82]
Hi,

I couldn’t find the method for recovering public address from signed data. In Eth you can use web3.eth.personal.sign(data, address) and then later use recover or ecrecover to get the address from the signature.

Is something similar possible? Or nothing like this implemented yet? (Thinking about implementing login flow with Comet)

Thanks

**Comment by bradleySuira** [comment]
Hi @adaaaam7777 maybe this example can help you, this is with thorify, not sure how do the same with connex/comet:

```
const address = 'your_address';
const data = 'some data';
// 1: sign
const sign = thorify.eth.accounts.sign(data, address);

// 2: recover, need to use the same data 
const recoveredAddress = thorify.eth.accounts.recover(data, sign.signature);

// 3: check results, compare both address
if (thorify.utils.toChecksumAddress(recoveredAddress) === publicAddress) {
    console.log('SUCCESS');
 } else {
    console.log('FAILED');      
 }
```

Regards!

**Comment by libotony** [comment]
@adaaaam7777 As mentioned by @bradleySuira , thorify has implemented the accounts module in web3. There are two alternatives to implement login flow in DApps, one is using eth_sign in web3 the other one is applying for identity in signing service implemented in [connex](https://connex.vecha.in/#/?id=certificate-signing-service)

**Comment by adaaaam7777** [comment]
Ended up trying connex, because the accounts.sign on the Comet thor object requires privateKey, and I want to avoid it's use. However the connex sign service always generates a different signature for same message. Eg:

```
return signingService.request( {
			purpose: 'agreement',
			payload: {
				type: 'text',
				content: 'data'
			}
		} ).then( result => {
			console.log( 'result: ', result );
			return result.signature;
		} );
```
So how would I be able to recover the public address using connex?

**Comment by libotony** [comment]
The reason for different signature is connex compatible client(sync and comet) will add some meta info for the certificate, see [doc](https://connex.vecha.in/#/?id=perform-certificate-signing-request), for verifying connex signed cert please check [doc](https://github.com/vechain/thor-devkit.js#certificate)

**Comment by adaaaam7777** [comment]
Okay thanks for the help, finally solved it. I used connex signing service on the frontend (Comet injects thor and connex objects), and thorDevkit.Certificate.verify( cert ) for backend.
