### ISSUE TITLE
suggestion about readme

### ISSUE THREAD

**Issue by amazingandyyy** [vechain/thorify#9]
don't mess es5 and es6 code in one single file.

we can show both two versions 
## use it in es5
```javascript
const { thorify } = require("thorify");
const Web3 = require("web3");
```

## use it in es6
```javascript
import { thorify } from "thorify";
import Web3 = from "web3";
```

**Comment by libotony** [comment]
We suggest developer should know the difference between ES6 and ES5, but it's a good suggestion will add to the README

**Comment by libotony** [comment]
updated in #10
