### ISSUE TITLE
JSON RPC Error on net_version

### ISSUE THREAD

**Issue by marcomarasco** [vechain/thorify#91]
Hi there,
Got the following error during transactions.

```Error: Wrong response id "3477728465" (expected: "1") in {"jsonrpc":"2.0","id":1,"method":"net_version","params":[]}```

Wonder if there is a particular network id mapping to avoid this.

#### Environment information

SOLO MODE

Thorify version: `thorify version 1.2.0`
Web3 version: `web3 version 1.0.0-beta.37`

#### Expected behaviour

Detects local thor node, or a default value related to Ethereum.

#### Actual behaviour

Network ID always different on each transaction compared to 1

**Comment by libotony** [comment]
I think this is not an error from `thorify`, method `net_version` is not supported in `thorify`. Regarding the network ID, vechain distinguishes networks by chainTag, this is different from ethereum.

**Comment by marcomarasco** [comment]
Ok maybe it's an error related to web3-gear proxy.

> vechain distinguishes networks by chainTag, this is different from ethereum.
Good to know! How i can get this information through web3?

Thanks.

**Comment by libotony** [comment]
chianTag is the last byte of genesis block id

**Comment by libotony** [comment]
duplicate of vechain/web3-gear#30
